### PR TITLE
Addded withForwardHeaders() to forward the headers from one to other

### PR DESCRIPTION
**Pull request by shobhan1595**
Added this method to forward the headers from one service to another service ,through this method we can able to forward the headers .

### CODE REVIEW

**Comment by wellsb1** [comment]
@shobhan1595 I committed a change to this PR that is more in line with what we are looking for.  Can you please make a TestCase for the updated code as @gernblandston requested.  I understand the initial request was confusing.  Thanks!

**Comment by ishaqv** [comment]
> @shobhan1595 I committed a change to this PR that is more in line with what we are looking for. Can you please make a TestCase for the updated code as @gernblandston requested. I understand the initial request was confusing. Thanks!

I don't see the latest code not working. Following code found working 
public RestClient withForwardedHeaders(boolean forwardHeaders)
   {
     if (forwardHeaders){
        forcedHeaders.putAll(Chain.peek().getRequest().getHeaders());
     }
      return this;
   }
cc:@gernblandston

**Comment by wellsb1** [comment]
@ishaqv I did not understand your post.  The version of withForwardedHeaders you quoted in your last reply is absolutely incorrect.  withForwardedHeaders() should be called ONCE per RestClient during initial configuration in the orchestrator.  Then on every request if forwardHeaders is true, the RestClient pulls the current request headers out of Chain.peek().getRequest().getHeaders() and applies them to the outbound request.

**Comment by ishaqv** [comment]
> @ishaqv I did not understand your post. The version of withForwardedHeaders you quoted in your last reply is absolutely incorrect. withForwardedHeaders() should be called ONCE per RestClient during initial configuration in the orchestrator. Then on every request if forwardHeaders is true, the RestClient pulls the current request headers out of Chain.peek().getRequest().getHeaders() and applies them to the outbound request.

Here is what I did to test the code

1. created two api endpoints /first and /second.
2. Hit /first from postman with a header.
3. In the Action class linked with /first , created a RestClient with withForwardedHeaders(true).
4. Called /second using the RestClient previously created.
5. Tried to read headers in Action class linked with /second and found headers missing.

 I may be wrong but I am letting you know the test results.

**Comment by wellsb1** [comment]
@ishaqv did you try stepping through the RestClient code around line 373 to see what was going on?

**Comment by ishaqv** [comment]
> @ishaqv did you try stepping through the RestClient code around line 373 to see what was going on?
Line 375 - chain.first() returns null

**Pull request merged**
